<div class="postbox">
    <h3 class="hndle">
        <span><?php echo __('Site List', AAM_KEY); ?></span>
    </h3>
    <div class="inside" id="access-manager-inside">
        <div class="aam-postbox-inside">
            <table id="site-list" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Site ID</th>
                        <th>Site URL</th>
                        <th>Site Ajax URL</th>
                        <th width="85%"><?php echo __('Site Domain', AAM_KEY); ?></th>
                        <th><?php echo __('Action', AAM_KEY); ?></th>
                        <th>Main Site</th>
                        <th>Subdomain</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>